name: Generate TOC in all READMEs

on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  generate-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pathlib

      - name: Generate TOC in each README.md
        run: |
          python .github/scripts/generate_toc.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --cached --quiet || git commit -m 'Auto-generate TOC in READMEs'
          git push
